apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mywebapp-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: mywebapp-pv

